apiVersion: apps/v1
kind: Deployment
metadata:
  name: zytest
  labels:
    app: zytest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zytest
  template:
    metadata:
      labels:
        app: zytest
    spec:
      imagePullSecrets:
        - name: acr-secret   # 上面创建的secret名称
      containers:
        - name: zytest
          image: crpi-vyt22uhlh2w61g5u.cn-shanghai.personal.cr.aliyuncs.com/nmgkds/myrepo:master-5604a6c
          ports:
            - containerPort: 80
